version: '3.8'

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPass123!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dbacademy-network

  postgres-master:
    image: postgres:16
    container_name: postgres-master
    restart: always
    environment:
      POSTGRES_PASSWORD: RootPass123!
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dbacademy-network

  mongo-master:
    image: mongo:7.0
    container_name: mongo-master
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: RootPass123!
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - dbacademy-network

  redis-master:
    image: redis:7-alpine
    container_name: redis-master
    restart: always
    command: redis-server --requirepass RootPass123!
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dbacademy-network

  sqlserver-master:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-master
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: RootPass123!
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - dbacademy-network

volumes:
  mysql-data:
  postgres-data:
  mongo-data:
  redis-data:
  sqlserver-data:

networks:
  dbacademy-network:
    driver: bridge