version: '3.8'

services:
  multibdacademy-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multibdacademy-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"

    volumes:
      - ./MultiDBAcademy.Api/appsettings.json:/app/appsettings.json:ro

    networks:
      - dbacademy-network

networks:
  dbacademy-network:
    driver: bridge
